### ISSUE TITLE
Wrong CI detection with Codecov

### ISSUE THREAD

**Issue by thomasrockhu** [rosnovsky/rosnovsky.us#66]
Hi, Tom from Codecov here. I noticed that you were uploading coverage reports but not through a CI. We don't come across this use case a lot, and I'd love to know more about it or if this was done by mistake.

**Comment by rosnovsky** [comment]
Hey @thomasrockhu! It's probably just me doing stupid stuff. I used to use Codecov a few years back to get a nice coverage badge. Now I got to the point where I wanted to use it again. But unlike in the past, I couldn't find an easy way to just have my coverage uploaded to codecov on every commit, so I upload reports manually. I should probably learn how to do this the right way :)

**Comment by thomasrockhu** [comment]
@rosnovsky got it! how do you run tests currently and/or generate coverage?
